name: Setup PNPM
author: Cameron Clough
description: Setup PNPM for use in GitHub Actions

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - shell: bash
      run: pnpm install --frozen-lockfile

    - id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
