name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - name: get build info
        id: build_info
        run: echo timestamp=$(git show -s --format=%cI) >> $GITHUB_OUTPUT

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        env:
          VITE_APP_GIT_SHA: ${{ github.sha }}
          VITE_APP_GIT_TIMESTAMP: ${{ steps.build_info.outputs.timestamp }}

      - name: Upload built project
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          overwrite: true
          retention-days: 1
          name: build-artifacts-${{ github.run_id }}
