name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup GPG
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Sync fork
        id: sync
        run: |
          git remote add upstream https://github.com/commaai/new-connect.git
          git fetch upstream
          git rebase upstream/master
          synced=false
          if [ -n "$(git diff origin/main main --name-only)" ]; then
            synced=true
          fi
          echo "synced=$synced" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.sync.outputs.synced == 'true'
        run: |
          git add -A
          git commit --signoff -m "Update Flatpak dependencies"
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        if: steps.sync.outputs.synced == 'true'
        with:
          token: ${{ secrets.PAT }}
          branch: automated/upstream-update
          delete-branch: true
          title: Upstream Update
          body: Automated update from upstream
          labels: |
            update
            chore
            automated pr
            autorebase:opt-in
      - name: Automerge Pull Request
        if: steps.sync.outputs.synced && 'true' && (steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated')
        run: gh pr merge --rebase --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
