name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build:development

      - name: Lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit

      - run: npx cypress install

      - name: Run end-to-end tests
        run: pnpm test:e2e

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: run Lighthouse CI
        run: pnpm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
