name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - run: |
          pnpm install --frozen-lockfile
          cd ./node_modules/puppeteer
          pnpm install --frozen-lockfile

      - run: pnpm run build:development

      - name: Lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run end-to-end tests
        run: pnpm test-puppeteer-build

  # bundle_size:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup-pnpm
  #     - uses: preactjs/compressed-size-action@v2
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #         build-script: build:production
  #         pattern: "./dist/assets/*.{css,js}"
  #         strip-hash: "\\b-\\w{8}"
  #         minimum-change-threshold: 100

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build:production

      - name: run Lighthouse CI
        run: |
          pnpm add -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
